name: Build/release

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - run: sudo wget 'https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64' -O /usr/bin/yq

      - name: Build
        run: ./compile.sh

      - name: Archive
        run: tar -czvf upload.tar.gz -C ./build .

      - name: Release
        run: 'curl -X POST -H "Authorization: Bearer ${{ secrets.DEPLOY }}" -F "upload=@upload.tar.gz" "https://sites.1f349.com/u?site=1f349.com&branch=${{ github.ref_name }}"'
